// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// readVCF
Rcpp::DataFrame readVCF(CharacterVector fname0);
RcppExport SEXP _BinaryDosageCompress_readVCF(SEXP fname0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type fname0(fname0SEXP);
    rcpp_result_gen = Rcpp::wrap(readVCF(fname0));
    return rcpp_result_gen;
END_RCPP
}
// mergeVCF2BD
void mergeVCF2BD(Rcpp::CharacterVector vcfFiles, Rcpp::CharacterVector bd_file_name0);
RcppExport SEXP _BinaryDosageCompress_mergeVCF2BD(SEXP vcfFilesSEXP, SEXP bd_file_name0SEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type vcfFiles(vcfFilesSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type bd_file_name0(bd_file_name0SEXP);
    mergeVCF2BD(vcfFiles, bd_file_name0);
    return R_NilValue;
END_RCPP
}
// writeVectorsToFile
void writeVectorsToFile(CharacterVector bd_file_name0, CharacterVector vcf_name0);
RcppExport SEXP _BinaryDosageCompress_writeVectorsToFile(SEXP bd_file_name0SEXP, SEXP vcf_name0SEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type bd_file_name0(bd_file_name0SEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type vcf_name0(vcf_name0SEXP);
    writeVectorsToFile(bd_file_name0, vcf_name0);
    return R_NilValue;
END_RCPP
}
// getStreamPositions
Rcpp::NumericVector getStreamPositions(CharacterVector fname0);
RcppExport SEXP _BinaryDosageCompress_getStreamPositions(SEXP fname0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type fname0(fname0SEXP);
    rcpp_result_gen = Rcpp::wrap(getStreamPositions(fname0));
    return rcpp_result_gen;
END_RCPP
}
// readSNP
Rcpp::DataFrame readSNP(CharacterVector fname0, int index0);
RcppExport SEXP _BinaryDosageCompress_readSNP(SEXP fname0SEXP, SEXP index0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type fname0(fname0SEXP);
    Rcpp::traits::input_parameter< int >::type index0(index0SEXP);
    rcpp_result_gen = Rcpp::wrap(readSNP(fname0, index0));
    return rcpp_result_gen;
END_RCPP
}
// readSNPwithPosition
Rcpp::DataFrame readSNPwithPosition(CharacterVector fname0, NumericVector pos0);
RcppExport SEXP _BinaryDosageCompress_readSNPwithPosition(SEXP fname0SEXP, SEXP pos0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type fname0(fname0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pos0(pos0SEXP);
    rcpp_result_gen = Rcpp::wrap(readSNPwithPosition(fname0, pos0));
    return rcpp_result_gen;
END_RCPP
}
// readSampleName
Rcpp::CharacterVector readSampleName(CharacterVector fname0);
RcppExport SEXP _BinaryDosageCompress_readSampleName(SEXP fname0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type fname0(fname0SEXP);
    rcpp_result_gen = Rcpp::wrap(readSampleName(fname0));
    return rcpp_result_gen;
END_RCPP
}
// getBDinfo
Rcpp::DataFrame getBDinfo(CharacterVector fname0);
RcppExport SEXP _BinaryDosageCompress_getBDinfo(SEXP fname0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type fname0(fname0SEXP);
    rcpp_result_gen = Rcpp::wrap(getBDinfo(fname0));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_BinaryDosageCompress_readVCF", (DL_FUNC) &_BinaryDosageCompress_readVCF, 1},
    {"_BinaryDosageCompress_mergeVCF2BD", (DL_FUNC) &_BinaryDosageCompress_mergeVCF2BD, 2},
    {"_BinaryDosageCompress_writeVectorsToFile", (DL_FUNC) &_BinaryDosageCompress_writeVectorsToFile, 2},
    {"_BinaryDosageCompress_getStreamPositions", (DL_FUNC) &_BinaryDosageCompress_getStreamPositions, 1},
    {"_BinaryDosageCompress_readSNP", (DL_FUNC) &_BinaryDosageCompress_readSNP, 2},
    {"_BinaryDosageCompress_readSNPwithPosition", (DL_FUNC) &_BinaryDosageCompress_readSNPwithPosition, 2},
    {"_BinaryDosageCompress_readSampleName", (DL_FUNC) &_BinaryDosageCompress_readSampleName, 1},
    {"_BinaryDosageCompress_getBDinfo", (DL_FUNC) &_BinaryDosageCompress_getBDinfo, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_BinaryDosageCompress(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
