# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

readVCF <- function(fname0) {
    .Call('_BinaryDosageCompress_readVCF', PACKAGE = 'BinaryDosageCompress', fname0)
}

mergeVCF2BD <- function(vcfFiles, bd_file_name0) {
    invisible(.Call('_BinaryDosageCompress_mergeVCF2BD', PACKAGE = 'BinaryDosageCompress', vcfFiles, bd_file_name0))
}

writeVectorsToFile <- function(bd_file_name0, vcf_name0) {
    invisible(.Call('_BinaryDosageCompress_writeVectorsToFile', PACKAGE = 'BinaryDosageCompress', bd_file_name0, vcf_name0))
}

getStreamPositions <- function(fname0) {
    .Call('_BinaryDosageCompress_getStreamPositions', PACKAGE = 'BinaryDosageCompress', fname0)
}

readSNP <- function(fname0, index0) {
    .Call('_BinaryDosageCompress_readSNP', PACKAGE = 'BinaryDosageCompress', fname0, index0)
}

readSNPwithPosition <- function(fname0, pos0) {
    .Call('_BinaryDosageCompress_readSNPwithPosition', PACKAGE = 'BinaryDosageCompress', fname0, pos0)
}

readSampleName <- function(fname0) {
    .Call('_BinaryDosageCompress_readSampleName', PACKAGE = 'BinaryDosageCompress', fname0)
}

getBDinfo <- function(fname0) {
    .Call('_BinaryDosageCompress_getBDinfo', PACKAGE = 'BinaryDosageCompress', fname0)
}

